name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Teste
      run: |
        # Executar a cobertura antes dos testes
        coverage run -m app_teste

    - name: Resultados
      run: coverage report

    - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      uses: docker/build-push-action@v5.3.0
          
